engines:
  pep8:
    enabled: true
  csslint:
    enabled: true
  duplication:
  	enabled: true
    config:
    	languages:
        - python
        - javascript
ratings:
  paths:
  - "**.py"
  - "src/*/**.py"
  - "src/*/**.css"
  - "src/*/**.js"
exclude_paths:
  - "__test__"
