language: python

python:
  - "3.6"

services:
  - mysql

env:
  - Flask=0.12.2 DB=mysql APP_SETTINGS=config.DevelopmentConfig

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - mysql -e 'create database traveler;' -u root

script:
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade
  - python manage.py cov
  - coverage run --source=src manage.py test

after_success:
  - coveralls

