language: python

python:
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev

services:
  - mysql

env:
  -Flask=0.12.2 DB=mysql

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - git clone git://github.com/kennethreitz/autoenv.git ~/.autoenv
  - echo 'source ~/.autoenv/activate.sh' >> ~/.bashrc
  - mysql -e 'create database traveler;' -u root
  - travis encrypt "APP_SETTINGS=config.DevelopmentConfig" --add

script:
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade
  - python manage.py test
  - coverage run --source=home manage.py test


after_success:
  - coveralls
  - CODECLIMATE_REPO_TOKEN=<token> codeclimate-test-reporter

